import type { Metadata } from "next"
import { JetBrains_Mono, Arima, Honk } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "next-themes"

const headingFont = Arima({ subsets: ["latin"], variable: "--font-heading" })
const displayFont = Honk({
  subsets: ["latin"],
  variable: "--font-display",
  axes: ["MORF", "SHLN"],
})
const monoFont = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        monoFont.variable,
        headingFont.variable,
        displayFont.variable
      )}
      suppressHydrationWarning
    >
      <body className="flex flex-col items-center justify-between lg:pt-6">
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  )
}
